package com.mikepenz.gradle.tasks

import org.gradle.api.provider.Property
import org.gradle.api.resources.ResourceHandler
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Sync

@CacheableTask
abstract class VersionTask : Sync() {
    @get:Input
    abstract val packageString: Property<String>

    @get:Input
    abstract val version: Property<String>

    @get:Input
    abstract val ideBuild: Property<Boolean>

    fun store(resourceHandler: ResourceHandler) {
        from(
            resourceHandler.text.fromString(
                """
                    // Autogenerated. Do not edit!
                    package ${packageString.get().trim()}
                    
                    const val VERSION = "${version.get()}"
                    const val IDE_BUILD = ${ideBuild.convention(false).get()}
                """.trimIndent().trim()
            )
        ) {
            rename { "Version.kt" }
            into(packageString.get().replace('.', '/'))
        }
    }
}